### ISSUE TITLE
[9.0.3] openvas-smb version check fail, will not break cmake

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvm-libs#116]
In the release notes version 1.0.4 of it are noted as minimum.
But using an old one will not let cmake fails:

-- Checking for module 'libopenvas_wmiclient>=1.0.4'
--   Requested 'libopenvas_wmiclient >= 1.0.4' but version of openvas-wmiclient is 1.0.3
-- Checking for module 'libopenvas_wincmd>=1.0.4'
--   Requested 'libopenvas_wincmd >= 1.0.4' but version of openvas-wmiclient is 1.0.3

**Comment by jjnicola** [comment]
Hello @tuxmaster5000,
this is the correct behavior, since openvas-smb is recommended (not mandatory) to have WMI support and it should not break cmake.
Regards,
Juan

**Comment by tuxmaster5000** [comment]
Ok, than I have miss understand it.
