### ISSUE TITLE
Libgcrypt warning: missing initialization during start of openvas-nasl

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gvm-libs#21]
When starting openvas-nasl, an warning will logged.

> openvas-nasl[24072]: Libgcrypt warning: missing initialization - please fix the application
Version: 9.0.1
command:

> OPENVAS_GPGHOME=/var/lib/openvas/gnupg openvas-nasl -p $(pwd)/ssh_proto_version.nasl

**Comment by kroosec** [comment]
Hi @tuxmaster, thanks for the report. Do you still see this warning ? Any difference between Master branch and OpenVAS-9, if so ?

I can't reproduce this, and haven't seen this warning reported since ages. Could it be due to an old libgcrypt version ?

**Comment by kroosec** [comment]
Not much to do without more useful information or similar reports. Closing.
