### ISSUE TITLE
Upload public key for the signature

### ISSUE THREAD

**Issue by shibumi** [greenbone/gvm-libs#221]
Hi,
I can't find your public GPG key on any keyserver, the public key is also not available under https://github.com/greenbone.gpg . Would be nice if you could upload it somewhere. Otherwise I can't verify your signature.

**Comment by jjnicola** [comment]
Hi @shibumi,
You can find the key to verify the signature here [https://community.greenbone.net/t/gcf-managing-the-digital-signatures/101](https://community.greenbone.net/t/gcf-managing-the-digital-signatures/101) to verify the signature.

**Comment by shibumi** [comment]
@jjnicola would be cool if the guys from openVAS could make this easier to find. Either through linking it to their github account or through linking it on their website on a prominent position.
