### ISSUE TITLE
missing -lgnutls

### ISSUE THREAD

**Issue by blshkv** [greenbone/gvm-libs#277]
Hi,

I'm trying to compile gvm from sources and facing the following error:

'''
md   main:MESSAGE:2019-10-13 14h38.24 utc:26507:    Greenbone Vulnerability Manager version 9.0.0~git (DB revision 221)
md manage:WARNING:2019-10-13 14h38.24 utc:26514: sql_exec_internal: PQexec failed: ERROR:  could not load library "/usr/lib64/libgvm-pg-server.so": /usr/lib64/libgvm_util.so.11: undefined symbol: gnutls_x509_privkey_import
 (7)
md manage:WARNING:2019-10-13 14h38.24 utc:26514: sql_exec_internal: SQL: CREATE OR REPLACE FUNCTION hosts_contains (text, text) RETURNS boolean AS '/usr/lib64/libgvm-pg-server', 'sql_hosts_contains' LANGUAGE C IMMUTABLE;
md manage:WARNING:2019-10-13 14h38.24 utc:26514: sqlv: sql_exec_internal failed
'''

The CMakefiles.txt seems missing **linking** gnutls in both static and dynamic sections

**Comment by blshkv** [comment]
That's a patch for sharing section

```
--- a/util/CMakeLists.txt.orig  2019-10-13 22:39:53.333743843 +0800
+++ b/util/CMakeLists.txt       2019-10-13 22:40:08.804743702 +0800
@@ -159,6 +159,7 @@
   target_link_libraries (gvm_util_shared LINK_PRIVATE ${GLIB_LDFLAGS}
                          ${GIO_LDFLAGS} ${GPGME_LDFLAGS} ${ZLIB_LDFLAGS}
                          ${RADIUS_LDFLAGS} ${LIBSSH_LDFLAGS}
+                         ${GNUTLS_LDFLAGS}
                          ${GCRYPT_LDFLAGS} ${LDAP_LDFLAGS} ${REDIS_LDFLAGS}
                          ${UUID_LDFLAGS} ${LINKER_HARDENING_FLAGS})
 endif (BUILD_SHARED)
```

**Comment by hsntgm** [comment]
Spent 2 hours for that :)
