### ISSUE TITLE
gvm-libs vulnerability

### ISSUE THREAD

**Issue by karkaaa** [greenbone/gvm-libs#351]
Hi, this week i get this CRITICAL vulnerability. It is bug? How to fix?

### Steps to reproduce

1. Run scan

### GVM versions

**gsa:** Greenbone Security Assistant 9.0.0~git-55b674481-gsa-9.0

**gvm:** Greenbone Vulnerability Manager 9.0.1~git-3e3d2350-gvmd-9.0

**openvas:** OpenVAS 7.0.0

**gvm-libs:** gvm-libs 11.0.1

### Environment

**Operating system:**
Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Installation method / source:** source installation

### Logfiles

```
```
![image](https://user-images.githubusercontent.com/34538939/84683522-fe272480-af3f-11ea-9e12-b670d5feff12.png)

**Comment by bjoernricks** [comment]
https://community.greenbone.net/t/frequently-asked-questions-faq/5558
