### ISSUE TITLE
Unable to compile gvm-libs 10.0.2 on CentOS 7

### ISSUE THREAD

**Issue by manju1920** [greenbone/gvm-libs#364]
I'm unable to install GVM libraries on CentOS 7.8 due to zlib version issue.

[root@openvas gvm-libs-10.0.2]# cmake3 .
-- Configuring the Greenbone Vulnerability Management Libraries...
-- Looking for clang-format...
-- clang-format not found...
-- Install prefix: /usr/local
-- Checking for module 'zlib>=1.2.8'
--   Requested 'zlib >= 1.2.8' but version of zlib is 1.2.7
CMake Error at /usr/share/cmake3/Modules/FindPkgConfig.cmake:497 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPkgConfig.cmake:681 (_pkg_check_modules_internal)
  util/CMakeLists.txt:33 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/root/gvm-libs-10.0.2/CMakeFiles/CMakeOutput.log".

Hence I downloaded zlib-1.2.11 and compiled manually and installed below path
/usr/src/zlib-1.2.11

still I'm getting above message.  Kindly help on this.

**Comment by bjoernricks** [comment]
The new zlib must be in the CMake search path for libraries. Most likely the C headers must be in `/usr/include` and the library itself be in `/usr/lib`. But nevertheless this is **NOT** an issue with our software. Therefore I am closing this issue.
