### ISSUE TITLE
Cpack create empty package

### ISSUE THREAD

**Issue by Taknok** [greenbone/gvm-libs#381]
### Expected behavior
Cpack should produce an archive with files inside.

### Actual behavior
Cpack (or make package) produce an empty archive.

### Steps to reproduce

- Optional, to ensure reproducibility:
1. `docker run -it ubuntu:20.04`
2. `apt update && apt install -y wget cmake pkg-config libglib2.0-dev libgpgme-dev libgnutls28-dev uuid-dev libssh-gcrypt-dev libldap2-dev libhiredis-dev libxml2-dev libradcli-dev libpcap-dev libgcrypt20-dev`
- Core:
1. `wget https://github.com/greenbone/gvm-libs/archive/v11.0.1.tar.gz`
2. `tar -xvf v11.0.1.tar.gz && cd gvm-libs-11.0.1/ && mkdir build && cd build/`
3. `cmake -DCMAKE_BUILD_TYPE=Release ..`
4. `cpack` or `make package`
5. `tar -tvf gvm-libs-11.0.1.tar.gz`

If using `make package_source` the archive is not empty (but contain only sources, which is normal).

### GVM versions

**gvm-libs:** v11.0.1

### Environment

**Operating system:**

DISTRIB_ID=Ubuntu                                                                                                                                     DISTRIB_RELEASE=20.04                                                                                                                                 DISTRIB_CODENAME=focal                                                                                                                                DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"

### Logfiles

```
# cpack
CPack: Create package using TGZ
CPack: Install projects
CPack: - Run preinstall target for: gvm-libs
CPack: - Install project: gvm-libs []
CPack: Create package
CPack: - package: /build/gvm-libs-11.0.1/build/gvm-libs-11.0.1.tar.gz generated.
#
```

**Comment by bjoernricks** [comment]
Oh I am sorry we aren't using cpack since a long time already. Please either use the git checkouts directly or download the release tarballs from github. cpack is just a leftover.
