### ISSUE TITLE
[20.8.0] unable to build the lib, during mising defines

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvm-libs#395]
OS: CentOS 7.8

Error first:
```
/builddir/build/BUILD/gvm-libs-20.8.0/boreas/alivedetection.c: In function 'scan':
/builddir/build/BUILD/gvm-libs-20.8.0/boreas/alivedetection.c:102:26: error: 'TH_SYN' undeclared (first use in this function)
       scanner.tcp_flag = TH_SYN; /* SYN */
                          ^
/builddir/build/BUILD/gvm-libs-20.8.0/boreas/alivedetection.c:102:26: note: each undeclared identifier is reported only once for each function it appears in
/builddir/build/BUILD/gvm-libs-20.8.0/boreas/alivedetection.c:110:26: error: 'TH_ACK' undeclared (first use in this function)
       scanner.tcp_flag = TH_ACK; /* ACK */
                          ^
make[2]: *** [boreas/CMakeFiles/gvm_boreas_shared.dir/alivedetection.c.o] Error 1
make[2]: Leaving directory `/builddir/build/BUILD/gvm-libs-20.8.0'
make[1]: *** [boreas/CMakeFiles/gvm_boreas_shared.dir/all] Error 2
```
Error second:
```
builddir/build/BUILD/gvm-libs-20.8.0/base/networking.c: In function 'ip_islocalhost':
/builddir/build/BUILD/gvm-libs-20.8.0/base/networking.c:841:18: error: 'addr.s_addr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
               if (addr_p->s_addr == sin->sin_addr.s_addr)
                  ^
cc1: all warnings being treated as errors
make[2]: *** [base/CMakeFiles/gvm_base_shared.dir/networking.c.o] Error 1
```

**Comment by marckll** [comment]
Hello @tuxmaster5000,
 
I am trying to compile gvm-libs on RHEL 7.9 and I am facing the same issue with TH_SYN and TH_ACK undeclared. I've applied your fix #396 but I am still getting the same error.

I've also tried to set directly the correct flags in the cmake command line : 
`cmake3 -DCMAKE_C_COMPILER=gcc -DCMAKE_C_FLAGS="-std=gnu99" -DCMAKE_INSTALL_PREFIX=/opt/gvm .. `
But still the same error. 

Can you confirm your fix only concerns the file boreas/CMakelists.txt with the following addition ? 
``` 
if (CMAKE_C_COMPILER_ID STREQUAL "GNU")
  if(${GLIB_VERSION} VERSION_LESS "2.50.3")
    add_definitions(-D_BSD_SOURCE)
  endif()
  add_compile_options(-std=gnu99)
endif()
```

Did you test this on CentOS 7 and get rid of the error ? And would you have an idea why I am still facing the issue after applying your fix on RHEL 7 ?

For info, I tested with both 20.08 and 20.8.1 releases.

Any help would be very much appreciated, thanks in advance !

**Comment by tuxmaster5000** [comment]
In general 3 patches are needed for modern c/c++ compilers like the 9'er form the RedHat devtool package. This is needed, because the old gcc 4 are to old. But i make the live easier, I have switched to the RHEL8 family, because the 3rd party libs are up to date. So you don't need bring your own versions of an long list of libs.

**Comment by zhuliantao** [comment]
Hello, I have the same problem when compiling

cenos 7.8

/home/openvas/openvas_new/gvm-libs-21.4.4/boreas/alivedetection.c: In function ‘scan’:
/home/openvas/openvas_new/gvm-libs-21.4.4/boreas/alivedetection.c:188:26: error: ‘TH_SYN’ undeclared (first use in this function); did you mean ‘MSG_SYN’?
       scanner.tcp_flag = TH_SYN; /* SYN */
                          ^~~~~~
                          MSG_SYN
/home/openvas/openvas_new/gvm-libs-21.4.4/boreas/alivedetection.c:188:26: note: each undeclared identifier is reported only once for each function it appears in
/home/openvas/openvas_new/gvm-libs-21.4.4/boreas/alivedetection.c:198:26: error: ‘TH_ACK’ undeclared (first use in this function)
       scanner.tcp_flag = TH_ACK; /* ACK */
                          ^~~~~~

**Comment by tuxmaster5000** [comment]
@zhuliantao  In the meantime I have switched to the RHEL8 family, which makes he live much easier, because the libs of it are up to date for the GSM world.

**Comment by ArnoStiefvater** [comment]
The <netinet/tcp.h> header needs to be available on the system. Our reference system is Debian buster/bullseye. Closing the issue because we are not able to support such old systems.
