### ISSUE TITLE
Signature key not available anymore

### ISSUE THREAD

**Issue by AquaL1te** [greenbone/gvm-libs#421]
In your documentation, a GPG key is mentioned: https://www.greenbone.net/GBCommunitySigningKey.asc
This file is not available anymore. Building GVM now fails in my container: https://github.com/AquaL1te/gvm/blob/main/Dockerfile

Please restore the GPG key, or update your documentation with the new URL that points to this key. Thank you.

**Comment by jjnicola** [comment]
Hello @AquaL1te 
thanks for reporting this issue. I am already on it.
Regards, 
Juan

**Comment by jjnicola** [comment]
The link has been repaired and it is working again. The key is available.
