### ISSUE TITLE
[9.0.2] cmake don't configure gpgme correct when not in default path

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gvm-libs#44]
When using an static version of gpgme, then cmake don't set the needed include/lib path.
Setting the path to the lib via the -DCMAKE_LIBRARY_PATH:PATH will allow cmake to detect the lib,
but the include and linker options are not added. So the build process fails:

> -- Looking for gpgme...
> -- Looking for gpgme... /builddir/build/BUILDROOT/openvas-libraries-9.0.2-1.el7.x86_64/helper/usr/lib64/libgpgme.a

....

> [ 15%] Building C object base/CMakeFiles/openvas_base_shared.dir/gpgme_util.c.o
> cd /builddir/build/BUILD/gvm-libs-9.0.2/base && /usr/lib64/ccache/cc  -Dopenvas_base_shared_EXPORTS -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/hiredis  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic  -Wformat -Wformat-security -O2 -D_FORTIFY_SOURCE=2 -fstack-protector -D_FILE_OFFSET_BITS=64 -Wall -Wextra -fPIC -g -Werror -fPIC   -DOPENVASSD_CONF=\"/etc/openvas/openvassd.conf\" -DOPENVAS_SYSCONF_DIR=\"/etc/openvas\" -DOPENVAS_STATE_DIR=\"/var/lib/openvas\" -DOPENVAS_PID_DIR=\"/var/run\" -o CMakeFiles/openvas_base_shared.dir/gpgme_util.c.o   -c /builddir/build/BUILD/gvm-libs-9.0.2/base/gpgme_util.c
> In file included from /builddir/build/BUILD/gvm-libs-9.0.2/base/gpgme_util.c:41:0:
> /builddir/build/BUILD/gvm-libs-9.0.2/base/gpgme_util.h:36:19: fatal error: gpgme.h: No such file or directory
>  #include <gpgme.h>

gpgme-config --libs:

> -L/builddir/build/BUILDROOT/openvas-libraries-9.0.2-1.el7.x86_64/helper/usr/lib64 -lgpgme -lassuan -lgpg-error

gpgme-config --cflags:

> -I/builddir/build/BUILDROOT/openvas-libraries-9.0.2-1.el7.x86_64/helper/usr/include

The whole gpgme-config stuff is missing in the compile command.
And the right gpgme-config tool will be used:
which gpgme-config:

> /builddir/build/BUILDROOT/openvas-libraries-9.0.2-1.el7.x86_64/helper/usr/bin/gpgme-config

**Comment by tuxmaster** [comment]
grep -R GPGME_CFLAGS

> ChangeLog:	* base/CMakeLists.txt: Add GPGME_CFLAGS to compiler flags. Patch
> CMakeLists.txt:    OUTPUT_VARIABLE GPGME_CFLAGS

It looks like, the  GPGME_CFLAGS value is collected, but never used.

**Comment by tuxmaster** [comment]
Patch for it:
diff -Nur gvm-libs-9.0.2.org/base/CMakeLists.txt gvm-libs-9.0.2/base/CMakeLists.txt
--- gvm-libs-9.0.2.org/base/CMakeLists.txt      2018-03-21 07:48:17.480411065 +0100
+++ gvm-libs-9.0.2/base/CMakeLists.txt  2018-03-21 07:58:27.857001208 +0100
@@ -50,7 +50,7 @@
 
 endif (NOT MINGW)
 
-include_directories (${GLIB_INCLUDE_DIRS} ${ZLIB_INCLUDE_DIRS} ${REDIS_INCLUDE_DIRS})
+include_directories (${GLIB_INCLUDE_DIRS} ${ZLIB_INCLUDE_DIRS} ${REDIS_INCLUDE_DIRS} ${GPGME_INCLUDE_DIRS})
 
 if (MINGW)
   set  (FILES array.c credentials.c openvas_hosts.c cvss.c nvti.c nvticache.c
diff -Nur gvm-libs-9.0.2.org/CMakeLists.txt gvm-libs-9.0.2/CMakeLists.txt
--- gvm-libs-9.0.2.org/CMakeLists.txt   2018-03-21 07:48:17.480411065 +0100
+++ gvm-libs-9.0.2/CMakeLists.txt       2018-03-21 08:17:30.260510767 +0100
@@ -236,6 +236,7 @@
   execute_process (COMMAND gpgme-config --cflags
     OUTPUT_VARIABLE GPGME_CFLAGS
     OUTPUT_STRIP_TRAILING_WHITESPACE)
+  string(REPLACE "-I" "" GPGME_INCLUDE_DIRS ${GPGME_CFLAGS})
 
   message (STATUS "Looking for netsnmp...")
   find_library (SNMP snmp)
@@ -258,6 +259,7 @@
     execute_process (COMMAND libgcrypt-config --cflags
       OUTPUT_VARIABLE GCRYPT_CFLAGS
       OUTPUT_STRIP_TRAILING_WHITESPACE)
+    string(REPLACE "-I" "" GCRYPT_INCLUDE_DIRS ${GCRYPT_CFLAGS})
   endif (NOT GCRYPT)
 
 endif (NOT MINGW)
diff -Nur gvm-libs-9.0.2.org/misc/CMakeLists.txt gvm-libs-9.0.2/misc/CMakeLists.txt
--- gvm-libs-9.0.2.org/misc/CMakeLists.txt      2018-03-21 07:48:17.479411056 +0100
+++ gvm-libs-9.0.2/misc/CMakeLists.txt  2018-03-21 08:09:02.294834023 +0100
@@ -26,6 +26,7 @@
 
 include_directories (${GLIB_INCLUDE_DIRS})
 include_directories (${GNUTLS_INCLUDE_DIRS})
+include_directories (${GCRYPT_INCLUDE_DIRS})
 
 if (MINGW)
   if (CROSS_ENV)

**Comment by bjoernricks** [comment]
@tuxmaster just create a PR if you have already written a patch. We are happy to merge it!

**Comment by tuxmaster** [comment]
Fix for the master.
#45

**Comment by tuxmaster** [comment]
Closed, because fix was integrated into master.
And for the 9.0.2 the patch are above.
