### ISSUE TITLE
[21.4.1] Source code signature is missing

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvm-libs#536]
The gpg signature for the tar ball is missing.

**Comment by bjoernricks** [comment]
It is uploaded already.

**Comment by y0urself** [comment]
Not anymore. :)

Sadly we have not found out how to automate that step, since gpg prompts for the password. You are welcome to help me find a solution to use gpg without prompting for the PW. :)

**Comment by tuxmaster5000** [comment]
@y0urself I Think you can use an gpg-agent. So you must only enter the password on the first key usage.

**Comment by y0urself** [comment]
> @y0urself I Think you can use an gpg-agent. So you must only enter the password on the first key usage.

Yeah. That's what we already use. I thought about something that does not require to enter the password in a prompt, but given as a parameter ...
