### ISSUE TITLE
[21.4.1] source code verification fails.

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvm-libs#537]
The verification of the source code will fail:

> LANG=C gpg --verify SOURCES/v21.4.1.tar.gz.asc  SOURCES/gvm-libs-21.4.1.tar.gz
> gpg: Signature made Wed Jun 23 14:44:31 2021 CEST
> gpg:                using RSA key 8AE4BE429B60A59B311C2E739823FAA60ED1E580
> gpg: BAD signature from "Greenbone Community Feed integrity key" [unknown

It looks like the key is correct.

**Comment by y0urself** [comment]
Should be fixed. Thx for the information!

**Comment by tuxmaster5000** [comment]
Yes now all is fine. Thanks
