### ISSUE TITLE
[21.4.2] Source code signature is missing

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvm-libs#573]
The .asc file for the tar ball is missing.

**Comment by y0urself** [comment]
really?

**Comment by tuxmaster5000** [comment]
Yes, on the download page only the tar and zip file was present.

**Comment by tuxmaster5000** [comment]
Are now the files are present.
Are the files generated later, so it was missing before?

**Comment by y0urself** [comment]
Maybe, because the signing has to be done manually and it was not ready.
We do not forget the signing - just don't expect it to be ready, if you want to use the new version within 5 minutes.
