### ISSUE TITLE
Where do I find the password?

### ISSUE THREAD

**Issue by S3j5b0** [greenbone/gvm-libs#591]
Hi, I'm attempting to setup gvm on a kali vm.

I found [https://linuxhint.com/install-openvas-kali-linux/](this) tutorail and followed it as well as I could.

The setup here basically consists of just running: 

```
 $ sudo apt-get install openvas
$ sudo gvm-setup
```
and then run by typing `sudo gvm-start`.
In the tutorial, it says that my password will be generated while running the setup command. But I really can't find anything in the output.

My output looks like this (I have excluded the part that is just files):
![image](https://user-images.githubusercontent.com/44634922/135901720-e087d365-6669-4fef-a4f8-67bf6de7f727.png)

![image](https://user-images.githubusercontent.com/44634922/135901788-82e0ffec-2a00-4faa-b5a2-bba8398d7ec6.png)

I've been trying to look through the manpage for hints on how to change the password.. I found the command 

`sudo gvmd --new-password=pw`

To which it says `user required`. But I don't understand where I should input a username, or from where I should know what my username is?

**Comment by y0urself** [comment]
That is the password for the user `kali` on your machine. For any more information you may search for `sudo`, what it does, why it is used. Etc. pp.

**Comment by cfi-gb** [comment]
For questions around the setup please also use the community portal:

https://community.greenbone.net
