### ISSUE TITLE
"optional" mqtt support in 'main' does not appear to be optional

### ISSUE THREAD

**Issue by immauss** [greenbone/gvm-libs#632]
The mqtt support is listed as optional in the INSTALLmd, but I can't seem to find a way to build gvm-libs without it. 

### Expected behavior
Able to not build 'optional' components.

### Actual behavior
Builds fail with out the dependency and the dependency is not easily located or part of the stated build environment for the rest of GVM.

**Comment by bjoernricks** [comment]
Are you trying to build the main branch? mqtt should not be included in the stable and oldstable branches. For main it is actually required.

**Comment by immauss** [comment]
yes. trying to build from main. 
Thanks.

**Comment by bjoernricks** [comment]
You should really not build from main. It is our development branch and may break everytime.

**Comment by immauss** [comment]
Yes. I know..... 
I had a specific goal in mind. I was trying to get as far as I could without opening a ticket here for it, but I'm probably going to need to anyway as I'm not having any success. I mentioned it earlier in the forums, but openvas 21.4.3 is segfaulting when I run it in a container. At some point, someone told me they had used the stable build of openvas with my container and it did not segfault, but I did not see the same, so I was trying to go down the path of getting the entire thing built on stable vs release to see if it worked out, but no luck.  I'll try to gather as much data as I can before I open the issue. 

Thanks,
Scott
