### ISSUE TITLE
Openvas scanner would pending infinitely Because of misuse of pthread_cond_signal

### ISSUE THREAD

**Issue by shixw2000** [greenbone/gvm-libs#639]
### Expected behavior
Openvas scanner CanNot finish a task but wait infinitely, Though all alive targets have finished the dectetions.

### Actual behavior
It is Occasionally that the main process of the task would pending infinitely at the point:
In file: <boreas/sniffer.c>, the parent thread
  Funcs: <start_sniffer_thread> 
		err = pthread_create (sniffer_thread_id, NULL, sniffer_thread, scanner);
		...
        pthread_mutex_lock (&mutex);
   ===> pthread_cond_wait (&cond);      //point 1
		pthread_mutex_unlock (&mutex);
Is conflict with child thread
  Funcs: <sniffer_thread> 
		pthread_mutex_lock (&mutex);
   ===> pthread_cond_signal (&cond);   //point 2
		pthread_mutex_unlock (&mutex);
		
If the child thread function pthread_cond_signal happens before the parent pthread_cond_wait, 
 then the parent will pend at point 1 forever.
 In <start_sniffer_thread>, <pthread_mutex_lock> must be placed before pthread_create to avoid the Dead case.

### Steps to reproduce
Start a simple task with target's 'Alive Test' method isnot 'Consider Alive'.

### GVM versions
**gvm-libs: All

### Environment

**Operating system:**

Linux

**Installation method / source:** (packages, source installation)

### Logfiles

```
```

**Comment by ArnoStiefvater** [comment]
Thanks a lot for the report.
Got fixed with https://github.com/greenbone/gvm-libs/pull/640.
